[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font]
size = 10

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Control | Shift"

[terminal.shell]
program = "/usr/bin/tmux"

[window]
startup_mode = "Maximized"
# dynamic_title = false
