require "user.impatient"
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.autocommands"
require "user.cmp"
require "user.telescope"
require "user.gitsigns"
require "user.autopairs"
require "user.comment"
require "user.nvim-tree"
require "user.lualine"
require "user.alpha"
require "user.lsp"

-- require "user.treesitter"
-- require "user.colorscheme"
